# imports
import pandas as pd
import sys
import importlib.util
import traceback
from stat_genie.blade_pipeline.llms.config import llm

def is_code_correct(code_name: str,
                    code_path: str,
                    code_purpose: str,
                    dataset_path: str = None,
                    model_output = None,
                    verbose: bool=False) -> str:
    """
    Given a path to an LLM-generated Python file, check if the module can be
    imported without errors. This includes checking that the file includes the
    necessary functions for its purpose. If there are no issues with the file,
    it returns `True`. If there are any issues, it returns `False`.
    
    Args:
        code_name (str): The name of the code file.
        code_path (str): The path to the code file.
        code_purpose (str): The purpose of the code. Must be either
                            'transform_model' or 'final_answer'.
        dataset_path (str): The path to the dataset. Only required if the
                            'code_purpose' is 'transform_model'.
        model_output: The output of the model function. Only required if the
                      'code_purpose' is 'final_answer'.
        verbose (bool): Whether to print detailed error messages.
    
    Returns:
        str: None if the code is correct, otherwise the error message to pass
             back to the LLM.
    """
    
    # handle code purposes
    if code_purpose == 'transform_model':
        assert dataset_path is not None, \
            "Parameter `dataset_path` must be provided when \
            `code_purpose` is 'transform_model'"
        functions = ['transform', 'model']
    elif code_purpose == 'final_answer':
        assert model_output is not None, \
            "Parameter `model_output` must be provided when \
            `code_purpose` is 'final_answer'"
        functions = ['extract_final_answer']
    else:
        raise ValueError("Parameter `code_purpose` must be either \
            'transform_model' or 'final_answer'")
    
    ### check for syntax errors and required functions ###
    try:
        # rename module to start with _ to avoid reloading errors
        code_name = f"_{code_name}"
        
        # check that code file has no syntax errors
        spec = importlib.util.spec_from_file_location(code_name,
                                                      code_path)
        module = importlib.util.module_from_spec(spec)
        sys.modules[code_name] = module
        spec.loader.exec_module(module)
        
        # check that required functions are present
        for function in functions:
            if not hasattr(module, function):
                msg = f"Error: '{function}' function not found."
                if verbose:
                    print(msg)
                return msg
    except Exception as e:
        error_trace = traceback.format_exc()
        msg = f"Error prior to runtime:\n{error_trace}"
        if verbose:
            print(msg)
        return msg

    ### check for runtime errors ###
    try:
        # get the functions
        if code_purpose == 'transform_model':
            
            # get the functions
            transform_func = module.transform
            model_func = module.model
            
            # read in the dataset
            df = pd.read_csv(dataset_path)
            
            # run the transform function
            transformed_df = transform_func(df)
            
            # run the model function
            model_results = model_func(transformed_df)
        
        elif code_purpose == 'final_answer':
            
            # get the functions
            final_answer_func = module.extract_final_answer
            
            # run the extract_final_answer function
            final_answer = final_answer_func(model_output)
        
        else:
            raise ValueError("Parameter `code_purpose` must be either \
                'transform_model' or 'final_answer'")
    except Exception as e:
        # error_trace = traceback.format_exc() # issues with patsy compatibility
        trace_str = ''.join(traceback.format_tb(e.__traceback__))
        err_and_trace = trace_str + f"{type(e).__name__}: {e}"
        msg = f"Error during runtime:\n{err_and_trace}"
        if verbose:
            print(msg)
        return msg
    
    return None

def llm_correction(code_path: str, error_message: str, code_purpose: str,
                   llm_provider: str, llm_model: str) -> str:
    """
    Given the path of an LLM-generated Python file and an error
    message, this function requests corrections from the LLM. It reads the 
    content of the file and constructs a prompt including the error message.
    The corrected code generated by the LLM will then be written to the same
    file path.
    
    Args:
        code_path (str): The file path to the analysis code.
        error_message (str): The message indicating what is wrong with the code.
        code_purpose (str): The purpose of the code. Must be either
                            'transform_model' or 'final_answer'.
        llm_provider (str): LLM provider to use for corrections (e.g. OpenAI).
        llm_model (str): The LLM model to use for corrections (e.g. GPT-5).
    """
    # read in the code content
    with open(code_path, 'r') as file:
        code_content = file.read()
    
    # construct the system prompt
    code_fix_system_prompt = """
                             You are an expert Python programmer. Your task is
                             to fix issues in the provided code based on the
                             error message given. Ensure that the corrected code
                             adheres to best practices, is free of syntax
                             errors, and is consistent with the original intent
                             of the code as evidenced by the code's
                             documentation and contents as well as the user
                             prompt context provided.
                             """
                             
    # construct the user prompt
    if code_purpose == 'transform_model':
        code_fix_user_prompt = f"""
                            <code>
                            {code_content}
                            </code>
                            
                            The above Python code should define two functions:
                           
                            The transform function which follows the which will take the original dataframe \
                            and return the dataframe after all transformations. \
                            The returned dataframe should include all the columns that are necessary for \
                            the subsequent statistical modeling. \
                            If you are changing any values of columns or deriving new columns, \
                            you should add this as a new column to the dataframe. \
                            Here is the code template for the transform function:
                            ```python
                            def transform(df: pd.DataFrame) -> pd.DataFrame:
                                # Your code here
                                return df
                            ```
                                
                            The model function which will take the transformed dataframe \
                            and run a statistical model on it. The model function should return the results of the model.
                            Here is the code template for the model function:
                            ```python
                            def model(df: pd.DataFrame) -> Any:
                                # Your code here
                                return results
                            ```

                            These functions should be able to run without errors. \
                            However, the current code has the following issue:
                            {error_message}
                            
                            Please provide a corrected version of the full code that resolves this issue. \
                            Your response should only include the corrected code file contents without any additional explanations, \
                            and should be able to be instantly converted into a .py file.
                            """
    elif code_purpose == 'final_answer':
        code_fix_user_prompt = f"""
                            <code>
                            {code_content}
                            </code>
                            
                            The above Python code should define one function, `extract_final_answer`:
                           
                            The function should:
                            - Take the model_output as input
                            - Extract the necessary statistics from the model output object
                            - Return a dictionary with:
                                - "object": The actual value you would like to return (e.g. a coefficient, p-value, etc.)
                                - "description": A brief explanation of the extracted statistics/return object and what it means in the context of the task
                            
                            Here is the code template for the extract_final_answer function:
                            ```python
                            def extract_final_answer(model_output):
                                # Your code here to extract and interpret statistics from model_output
                                # Return a dictionary with keys: "object", "description"
                                pass
                            ```

                            This function should be able to run without errors. \
                            However, the current code has the following issue:
                            {error_message}
                            
                            Please provide a corrected version of the full code that resolves this issue. \
                            Your response should only include the corrected code file contents without any additional explanations, \
                            and should be able to be instantly converted into a .py file.
                            """
    else:
        raise ValueError("Parameter `code_purpose` must be either \
            'transform_model' or 'final_answer'")
    
    # instantiate llm to fix problem
    llm_code_fixer = llm(provider=llm_provider, model=llm_model)
    
    # get the corrected code from the llm
    response = llm_code_fixer.generate([{"role": "system",
                                         "content": code_fix_system_prompt},
                                        {"role": "user",
                                         "content": code_fix_user_prompt}])
    corrected_code = response.text[0].content
    
    # replace the code file with the corrected code
    with open(code_path, 'w') as file:
        file.write(corrected_code)
    
    return

def check_and_fix_code(code_name: str,
                       code_path: str,
                       code_purpose: str,
                       llm_provider: str,
                       llm_model: str,
                       dataset_path: str = None,
                       model_output = None,
                       verbose: bool = False) -> int:
    """
    Given a Python file written by an LLM, this function checks if the code is
    correct. If the code is not correct, it requests corrections from the LLM
    and updates the file with the corrected code. If it takes more than ten
    iterations with an LLM to fix the code, the function stops and returns.
    
    Args:
        code_name (str): The name of the code file.
        code_path (str): The path to the code file.
        code_purpose (str): The purpose of the code. Must be either
                            'transform_model' or 'final_answer'.
        llm_provider (str): The LLM provider to use for corrections.
        llm_model (str): The LLM model to use for corrections.
        dataset_path (str): The path to the dataset. Only required if the
                            'code_purpose' is 'transform_model'.
        model_output: The output of the model function. Only required if the
                      'code_purpose' is 'final_answer'.
        verbose (bool): Whether to print detailed error messages.
    
    Returns:
        int: The number of iterations needed to fix the code. If the code was
             correct on the first check, returns 0. If it takes more than 10
             iterations, the function stops and returns -1.
    """
    
    # starts at zero iterations
    iterations = 0
    
    # initiate loop that only breaks when iter max has hit or code is correct
    while True:
        # append iteration count to the end of the analysis_code_name to avoid import issues
        code_name_iter = f"{code_name}_{iterations}"
        
        # call helper function above
        error_message = is_code_correct(code_name_iter,
                                        code_path,
                                        code_purpose,
                                        dataset_path=dataset_path,
                                        model_output=model_output,
                                        verbose=verbose)
        # None corresponds to correct code
        if error_message is None:
            break
        # iteration max, 10 is arbitrary but seems reasonable
        # needs to be here so if the 10th iteration fixes the code it counts
        if iterations >= 10:
            return -1
        # helper function which edits the file in place
        llm_correction(code_path, error_message, code_purpose, llm_provider,
                       llm_model)
        iterations += 1
    
    return iterations


def llm_correction_with_cvars(
    code_path: str,
    error_message: str,
    cvars_text: str,
    llm_provider: str,
    llm_model: str
) -> None:
    """
    Request code corrections from LLM with cvars constraints in the prompt.
    
    This is a cvars-aware version of llm_correction that includes
    the conceptual variables and their required column names in the prompt.
    
    Args:
        code_path: Path to the code file to fix
        error_message: Error message describing what's wrong
        cvars_text: Formatted text describing cvars and their columns
        llm_provider: LLM provider to use
        llm_model: LLM model to use
    """
    # Read the code content
    with open(code_path, 'r') as file:
        code_content = file.read()
    
    # System prompt
    code_fix_system_prompt = """
                             You are an expert Python programmer. Your task is
                             to fix issues in the provided code based on the
                             error message given. Ensure that the corrected code
                             adheres to best practices, is free of syntax
                             errors, and is consistent with the original intent
                             of the code as evidenced by the code's
                             documentation and contents as well as the user
                             prompt context provided.
                             """
    
    # User prompt with cvars constraints
    code_fix_user_prompt = f"""
                            <code>
                            {code_content}
                            </code>
                            
                            You are fixing Python code that defines TWO functions:

                            1. A transform function:

                                def transform(df: pd.DataFrame) -> pd.DataFrame:
                                    ...

                               This function reads a raw dataframe and returns a FINAL dataframe with all columns
                               needed for the statistical model.

                            2. A model function:

                                def model(df: pd.DataFrame) -> Any:
                                    ...

                               This function takes the FINAL dataframe (output of transform) and fits a statistical model.

                            ============================================================
                            CONCEPTUAL VARIABLES AND REQUIRED FINAL DATAFRAME COLUMNS
                            ============================================================

                            The conceptual variables and their REQUIRED FINAL dataframe columns are:

                            {cvars_text}

                            Each item above specifies:
                            - A conceptual variable (independent / dependent / control)
                            - The EXACT column name(s) in the FINAL dataframe that implement that variable.

                            These conceptual variables and their column names are ALREADY fixed and are used
                            elsewhere (e.g., in JSON outputs and evaluation). They MUST NOT change.

                            Your job is to fix the code so that it runs correctly WHILE STRICTLY PRESERVING
                            this contract.

                            ------------------------------------------------------------
                            HARD CONSTRAINTS YOU MUST FOLLOW
                            ------------------------------------------------------------

                            1. DO NOT change any of the column names listed in the block above.
                               - You MUST NOT rename, delete, or alter the spelling/casing of these columns
                                 anywhere in either the transform or model code.
                               - If the current code uses different names, you MUST change the CODE so that it
                                 uses the EXACT names listed above instead.

                            2. DO NOT change which columns the model uses as inputs for these conceptual variables.
                               - The identity and roles of IVs, DV, and controls are fixed by the conceptual
                                 variables and their associated column names above.
                               - You MUST NOT introduce new model input columns that are not in this list.
                               - You MUST NOT swap, drop, or reinterpret which column corresponds to which
                                 conceptual variable.

                            3. You MAY add internal helper columns inside the transform function, BUT:
                               - These helper columns are for intermediate computation only.
                               - They MUST NOT be treated as new conceptual variables.
                               - They MUST NOT be required inputs to the model beyond what is already
                                 specified by the conceptual variables block.
                               - The model's effective inputs (its formula, design matrix, etc.) must still
                                 ultimately be the same conceptual variables/columns listed above.

                            4. You MUST preserve the function signatures and return types:
                               - transform(df: pd.DataFrame) -> pd.DataFrame
                               - model(df: pd.DataFrame) -> Any

                            5. You MUST NOT change the high-level semantics of the analysis:
                               - The research question, conceptual meaning of variables, and their mapping
                                 to final dataframe columns must remain exactly the same.
                               - Assume that the JSON representation of the analysis (including cvars and
                                 their columns) is authoritative and must remain valid.

                            ------------------------------------------------------------
                            WHAT IS WRONG WITH THE CURRENT CODE
                            ------------------------------------------------------------

                            The current code has the following issue:

                            {error_message}

                            ------------------------------------------------------------
                            YOUR TASK
                            ------------------------------------------------------------

                            Please provide a corrected version of the FULL code file that:

                            - Fixes the issue described above so that the code runs without errors
                              when transform is applied to the dataset and model is called on the
                              transformed dataframe.
                            - STRICTLY respects all constraints about column names and conceptual
                              variables described above.
                            - May introduce internal helper columns ONLY as allowed above.

                            Your response MUST:

                            - Contain ONLY the corrected Python code file contents (no explanations).
                            - Be valid Python that can be saved directly as a .py file and imported.
                            """
    
    # Instantiate LLM to fix problem
    llm_code_fixer = llm(provider=llm_provider, model=llm_model)
    
    # Get the corrected code from the LLM
    response = llm_code_fixer.generate([{"role": "system",
                                         "content": code_fix_system_prompt},
                                        {"role": "user",
                                         "content": code_fix_user_prompt}])
    corrected_code = response.text[0].content
    
    # Replace the code file with the corrected code
    with open(code_path, 'w') as file:
        file.write(corrected_code)
    
    return


def check_and_fix_code_with_cvars(
    code_name: str,
    code_path: str,
    cvars_text: str,
    llm_provider: str,
    llm_model: str,
    dataset_path: str,
    verbose: bool = False
) -> int:
    """
    Check and fix code with cvars preservation constraints.
    
    This is a cvars-aware version of check_and_fix_code that ensures
    column names in cvars are preserved during fixing.
    
    Args:
        code_name: Name of the code file
        code_path: Path to the code file
        cvars_text: Formatted text describing cvars and their columns
        llm_provider: LLM provider to use for corrections
        llm_model: LLM model to use for corrections
        dataset_path: Path to the dataset
        verbose: Whether to print detailed error messages
        
    Returns:
        Number of iterations needed to fix the code (0 if already correct, -1 if max iterations reached)
    """
    iterations = 0
    max_iterations = 10
    
    while True:
        code_name_iter = f"{code_name}_{iterations}"
        
        # Check if code is correct
        error_message = is_code_correct(
            code_name_iter,
            code_path,
            'transform_model',
            dataset_path=dataset_path,
            verbose=verbose
        )
        
        # None means code is correct
        if error_message is None:
            break
        
        # Check iteration limit
        if iterations >= max_iterations:
            return -1
        
        # Fix the code with cvars constraints
        llm_correction_with_cvars(
            code_path,
            error_message,
            cvars_text,
            llm_provider,
            llm_model
        )
        iterations += 1
    
    return iterations
